In [1]:
import os
import pandas as pd
import xarray as xr
import datetime
import numpy as np

root_dir = '/glade/u/home/hongli/work/2020_04_21nldas_gmet'   
tmp_dir = 'data/nldas_daily_utc_convert'
ens_dir = '/glade/u/home/hongli/scratch/2020_04_21nldas_gmet/test_uniform/00986grids'

# nldas_file=os.path.join(root_dir,tmp_dir,'NLDAS_2015.nc')
# ens_mean = os.path.join(ens_dir,'tmp/ens_forc.2015.mean.nc')
# ens_bias = os.path.join(ens_dir,'tmp/ens_forc.2015.bias.nc')

# ens_raw_mb1 = os.path.join(ens_dir,'gmet_ens/ens_forc.2015.001.nc')
ens_crr_mb1 = os.path.join(ens_dir,'gmet_ens_bc/ens_forc.2016.001.nc')
ens_crr_mb2 = os.path.join(ens_dir,'gmet_ens_bc/ens_forc.2016.002.nc')
ens_crr_mb3 = os.path.join(ens_dir,'gmet_ens_bc/ens_forc.2016.003.nc')
ens_crr_mean = os.path.join(ens_dir,'gmet_ens_bc/test.mean.nc')

# # NLDAS pre-process
# f=xr.open_dataset(nldas_file)
# pcp_nldas = f.variables['pcp'][:]
# t_mean_nldas = f.variables['t_mean'][:]

# # bias calculation
# f=xr.open_dataset(ens_bias)
# pcp_bias = f.variables['pcp'][:]
# tmean_bias = f.variables['t_mean'][:]

# # bias correction
# f=xr.open_dataset(ens_raw_mb1)
# pcp_raw_mb1 = f.variables['pcp'][:]
# tmean_raw_mb1 = f.variables['t_mean'][:]

f=xr.open_dataset(ens_crr_mb1)
pcp_crr_mb1 = f.variables['pcp'][:]
tmean_crr_mb1 = f.variables['t_mean'][:]

f=xr.open_dataset(ens_crr_mb2)
pcp_crr_mb2 = f.variables['pcp'][:]
tmean_crr_mb2 = f.variables['t_mean'][:]

f=xr.open_dataset(ens_crr_mb3)
pcp_crr_mb3 = f.variables['pcp'][:]
tmean_crr_mb3 = f.variables['t_mean'][:]

f=xr.open_dataset(ens_crr_mean)
pcp_crr_mean = f.variables['pcp'][:]
tmean_crr_mean = f.variables['t_mean'][:]

print('Done')

/glade/u/home/hongli/tools/miniconda/ENTER/lib/python3.7/site-packages/xarray/core/merge.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)


Done


In [3]:
pcp_crr_mb1[0,200:203,100:103],pcp_crr_mb2[0,200:203,100:103],pcp_crr_mb3[0,200:203,100:103],pcp_crr_mean[0,200:203,100:103]

(<xarray.Variable (y: 3, x: 3)>
 array([[-0.01026 , -0.009715, -0.009124],
        [-0.012791, -0.012298, -0.010547],
        [-0.010418, -0.009811, -0.008301]], dtype=float32)
 Attributes:
     long_name:  estimated precip in mm/day
     units:      mm, <xarray.Variable (y: 3, x: 3)>
 array([[-0.01026 , -0.009715, -0.009124],
        [-0.012791, -0.012298, -0.010547],
        [-0.010418, -0.009811, -0.008301]], dtype=float32)
 Attributes:
     long_name:  estimated precip in mm/day
     units:      mm, <xarray.Variable (y: 3, x: 3)>
 array([[-0.01026 , -0.009715, -0.009124],
        [-0.012791, -0.012298, -0.010547],
        [-0.010418, -0.009811, -0.008301]], dtype=float32)
 Attributes:
     long_name:  estimated precip in mm/day
     units:      mm, <xarray.Variable (y: 3, x: 3)>
 array([[-0.01026 , -0.009715, -0.009124],
        [-0.012791, -0.012298, -0.010547],
        [-0.010418, -0.009811, -0.008301]], dtype=float32)
 Attributes:
     long_name:  estimated precip in mm/day
    

In [4]:
tmean_crr_mb1[0,200:203,100:103],tmean_crr_mb2[0,200:203,100:103],tmean_crr_mb3[0,200:203,100:103],tmean_crr_mean[0,200:203,100:103]

(<xarray.Variable (y: 3, x: 3)>
 array([[-6.834804, -7.176668, -7.312035],
        [-6.636008, -7.046214, -7.694464],
        [-6.347404, -6.840133, -7.133905]], dtype=float32)
 Attributes:
     long_name:  estimated daily mean temperature
     units:      deg_C, <xarray.Variable (y: 3, x: 3)>
 array([[-5.106459, -5.025153, -5.365837],
        [-5.042869, -5.474619, -5.941666],
        [-4.798742, -5.402901, -5.559571]], dtype=float32)
 Attributes:
     long_name:  estimated daily mean temperature
     units:      deg_C, <xarray.Variable (y: 3, x: 3)>
 array([[-4.516784, -4.935503, -5.177114],
        [-4.672942, -5.169597, -5.488084],
        [-4.448508, -4.890316, -5.01643 ]], dtype=float32)
 Attributes:
     long_name:  estimated daily mean temperature
     units:      deg_C, <xarray.Variable (y: 3, x: 3)>
 array([[-5.486015, -5.712441, -5.951662],
        [-5.450606, -5.89681 , -6.374738],
        [-5.198218, -5.711117, -5.903302]], dtype=float32)
 Attributes:
     long_name:  esti

In [7]:
(-6.834804-5.106459-4.516784)/3.0

-5.486015666666667