In [1]:
import os
import pandas as pd
import xarray as xr
import datetime
import numpy as np
import matplotlib.pyplot as plt

#----------------------------------------------------------
# read gmet output grids
grid_info_file = os.path.join(root_dir,'data/nldas_topo/conus_ens_grid_eighth.nc')
f = xr.open_dataset(os.path.join(root_dir,grid_info_file))
mask_grid_info = f['mask'].values[:] # 1 is valid. 0 is invalid. 
latitude = f['latitude'].values[:] 
longitude = f['longitude'].values[:] 
elev = f['elev'].values[:] 
gradient_n_s = f['gradient_n_s'].values[:] 
gradient_w_e = f['gradient_w_e'].values[:] 

print('Done')

/glade/u/home/hongli/tools/miniconda/ENTER/lib/python3.7/site-packages/xarray/core/merge.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)


Done


In [27]:
j=175
i=100 #99
latitude[i,j],longitude[i,j],elev[i,j],gradient_n_s[i,j],gradient_w_e[i,j]

(37.4375,
 -103.0625,
 1511.4019775390625,
 0.25196197628974915,
 0.10644451528787613)

In [29]:
99*464+175+1

46112

In [7]:
# read gmet regression result
import os
import pandas as pd
import xarray as xr
import datetime
import numpy as np
import matplotlib.pyplot as plt

#----------------------------------------------------------
# read gmet regression output
grid_info_file = '/glade/u/home/hongli/scratch/2020_04_21nldas_gmet/test_uniform_debug/00810grids/gmet_regr/regress_ts.weight.nc'
f = xr.open_dataset(grid_info_file)
latitude = f['latitude'].values[:] 
longitude = f['longitude'].values[:] 
pop = f['pop'].values[:] 
pcp = f['pcp'].values[:] 
tmean = f['tmean'].values[:] 
trange = f['trange'].values[:] 

print('Done')

Done


In [28]:
j=175
i=99
latitude[i,j],longitude[i,j],pop[0,i,j],pcp[0,i,j],tmean[0,i,j],trange[0,i,j]

(37.4375, -103.0625, 0.5, 0.0, 0.0, 0.0)

In [1]:
# read gmet regression result
import os
import pandas as pd
import xarray as xr
import datetime
import numpy as np
import matplotlib.pyplot as plt

#----------------------------------------------------------
# read gmet regression output (problem one)
grid_info_file = '/glade/u/home/hongli/scratch/2020_04_21nldas_gmet/test_uniform/00810grids/gmet_regr/regress_ts.weight.nc'
f = xr.open_dataset(grid_info_file)
latitude = f['latitude'].values[:] 
longitude = f['longitude'].values[:] 
pop = f['pop'].values[:] 
pcp = f['pcp'].values[:] 
tmean = f['tmean'].values[:] 
trange = f['trange'].values[:] 

print('Done')

/glade/u/home/hongli/tools/miniconda/ENTER/lib/python3.7/site-packages/xarray/core/merge.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)


Done


In [18]:
j=175
i=100 #99
latitude[i,j],longitude[i,j],pop[0,i,j],pcp[0,i,j],tmean[0,i,j],trange[0,i,j]

(49.3125,
 -109.6875,
 0.6201223134994507,
 -0.11529640853404999,
 -4.610972881317139,
 5.8117356300354)

In [1]:
# read gmet input stndata
import os
import pandas as pd
import xarray as xr
import datetime
import numpy as np
import matplotlib.pyplot as plt

#----------------------------------------------------------
# read gmet regression output
grid_info_file = '/glade/u/home/hongli/scratch/2020_04_21nldas_gmet/scripts/step2_prepare_stndata_uniform/stndata_00810grids/Row220Col460.nc'
f = xr.open_dataset(grid_info_file)

elevation = f['elevation'].values[:] 
latitude = f['latitude'].values[:] 
longitude = f['longitude'].values[:] 
prcp = f['prcp'].values[:] 
tmax = f['tmax'].values[:] 
tmin = f['tmin'].values[:] 

print('Done')

/glade/u/home/hongli/tools/miniconda/ENTER/lib/python3.7/site-packages/xarray/core/merge.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)


Done


In [2]:
latitude,longitude

(array([52.5625], dtype=float32), array([-67.4375], dtype=float32))

In [7]:
tmax[0:10],tmin[0:10]

(array([-15.149994, -15.130005, -23.87999 , -14.139984, -13.779999,
        -20.87999 , -25.069992, -26.09999 , -17.949997, -18.509995],
       dtype=float32),
 array([-25.419998, -23.539993, -27.759995, -27.069992, -19.519989,
        -26.079987, -26.769989, -29.89    , -27.159988, -28.569992],
       dtype=float32))

In [6]:
np.shape(tmin)

(731,)